language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install
  - npm install hexo-renderer-pug --save
  - npm install hexo-renderer-sass --save
  - npm install hexo-generator-feed

#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "ghosthim"
  - git config user.email "ghosthim007@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
  - git push --force --quiet "https://ghosthim:${CO_TOKEN}@${CO_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog
env:
 global:
   - GH_REF: github.com/ghosthim/blog.api2u.cn.git
   - CO_REF: git.coding.net/ghosthim/blog.api2u.cn.git
