baseURL = "https://blog.api2u.me"
languageCode = "en-us"
title = "api2u's Blog"
theme = "yinyang"
DefaultContentLanguage = "cn"

[author]
  name = "api2u"
  homepage = "https://api2u.me"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1
  [languages.cn]
    contentDir = "content/cn"
    languageName = "Chinese"
    weight = 2

[params]
mainSections = ["posts"]
headTitle = "api2u"
[[params.socials]]
name = "About Me"
link = "https://api2u.me"
[[params.socials]]
name = "Github"
link = "https://github.com/ghosthim"
postHeaderContent = ""
postFooterContent = ""
# extraCSSFiles = ["css/foo.css", "css/bar.css"]
extraCSSFiles = []