
# 站点关键字
keywords: "api2u Blog"

# 建站日期
since: 2015

# 导航栏
menu:
  Home: /
  About: /about
  Movies: /movies
  History: /history
  #API: https://openapi.link/

# 联系方式
social:
  QQ:
  邮箱: i@api2u.me
  微博:
  GitHub: ghosthim
  Coding:

# 底部字数统计，需安装 hexo-wordcount 插件
# 安装命令 npm install hexo-wordcount，然后启用为 enabled
footer_wordcount: enabled

# 底部版权补充
footer_expand: 'Hosted by <a href="https://www.aliyun.com/product/oss">Aliyun OSS</a>, '

# 站点微缩图
favicon: /favicon.ico

# 站点 Logo
logo: /favicon.png

# 一言 hitokoto
hitokoto: disabled

# 百度站点验证
baidu_verification: 

# Gitment
gitment:
  owner: ghosthim
  repo: api2u-cdn
  client_id: a27e7b3219037d96a5ca
  client_secret: 6898411f4f3956f1fd0ee76b5f4f0c689e24128d

# 腾讯统计
tencent_analytics: 

# CSS 样式表路径
stylesheets:
- /css/fonts.css
- /css/font-awesome.min.css
- /css/gitment.css
- /css/highlight.css
- /css/hola.css
- /css/alu.css

# Javascript 脚本路径
scripts:
- /js/jquery.min.js
- /js/fetch.min.js
- /js/md5.min.js
- /js/instantclick.min.js
- /js/gitment.browser.min.js
- /js/hola.js
- /js/alu.min.js
- /js/alu.js
